StandHumanoidController:
  type: controller/StandHumanoidController
DampingHumanoidController:
  type: controller/DampingHumanoidController
MimicHumanoidController:
  type: controller/MimicHumanoidController